### ISSUE TITLE
errror launch on macos 10.13.4 

### ISSUE THREAD

**Issue by fyeeme** [thejandroman/bing-wallpaper#20]
error is below:
<pre>
bing-wallpaper.sh: line 97: syntax error near unexpected token `('
bing-wallpaper.sh: line 97: `read -ra urls <<(curl -sL $PROTO://www.bing.com | \'
<pre>

**Comment by thejandroman** [comment]
@fyeeme it looks like the code on line 97 was modified from what's in [master](https://github.com/thejandroman/bing-wallpaper/blob/master/bing-wallpaper.sh#L97) ([canonical link](https://github.com/thejandroman/bing-wallpaper/blob/29461fbd558ca8ba79423fb95ce88f9d59d18d79/bing-wallpaper.sh#L97)). If you revert that change it should start working again.

**Comment by fyeeme** [comment]
@thejandroman, yeah, really solve the problem,  thank you,buddy

**Comment by fyeeme** [comment]
@thejandroman  so why not consider to revert the code ?

**Comment by thejandroman** [comment]
The code is correct in master. I'm not sure how your code got in that state. I'm glad things are working for you.
