### ISSUE TITLE
UHD

### ISSUE THREAD

**Issue by Mateus109** [thejandroman/bing-wallpaper#43]
Bing wallpapers are now available in UHD 5935 × 3338 (e.g. https://www.bing.com/th?id=OHR.HogwartsExpress_EN-GB7641570883_UHD.jpg) and also 3840x2160.

**Comment by thejandroman** [comment]
UHD was added in #44 but I wasn't able to figure out how to add 3840x2160 support. Do you have a sample URL?

**Comment by Mateus109** [comment]
The image sizes for the _UHD variants all seems a bit random, perhaps they're the original photos and Microsoft have just stuck _UHD on the end.  e.g. today's image is 5889 × 3313, yesterdays was 7348 × 4133, Sunday's 6108 × 3436, etc.
I'm grabbing them with:
`$match = [];
if (!preg_match('/<urlBase>(.+)<\/urlBase>/', $xml, $match)) {
  die();
}
$url = 'http://www.bing.com' . $match[1] . '_UHD.jpg';`
