### ISSUE TITLE
Script fails on MacOS Monterey (12.4) because grep does not support -P option

### ISSUE THREAD

**Issue by 2h4u** [thejandroman/bing-wallpaper#45]
The current version of this script (0.5.0) does not work on macOS Monterey because it fails with the following error:
```
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
            [-e pattern] [-f file] [--binary-files=value] [--color=when]
            [--context[=num]] [--directories=action] [--label] [--line-buffered]
            [--null] [pattern] [file ...]
```

I checked the man pages of grep and there seems to be no option that does something similar.

So in my mind there are 3 options:
1. replace the grep -Po with the previously used grep -Eo
2. provide a tutorial how to update/change grep on macOS
3. drop macOS support for this script

**Comment by ErnestDong** [comment]
you can use gnu grep instead of bsd grep, which is
```sh
brew install grep # and add path to your config
```

**Comment by rocdeng** [comment]
You can try this: using ggrep

https://apple.stackexchange.com/questions/193288/how-to-install-and-use-gnu-grep-in-macos

**Comment by 2h4u** [comment]
Thanks for the hints, but I already wrote my own app for that 😄
https://github.com/2h4u/BingWallpaper-for-Mac
